language: nix
nix: 2.2.1


before_script:
- nix-env -iA cachix -f https://cachix.org/api/v1/install
- cachix use yurrriq


jobs:
  include:
    - stage: Build
      name: "Tangle source code"
      script: nix-build -A dev
    - name: "Build binaries"
      script: nix-build
    - stage: "Generate Documentation"
      name: "Weave PDF"
      script: nix-build -A docs
    - name: "Generate documentation"
      script: nix-shell --run doxygen
